name: net-tools
on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Set image variables
      - name: Set image name and tag
        run: |
          echo "IMAGE=${{ secrets.DOCKER_USERNAME }}/utils" >> $GITHUB_ENV
          echo "GIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      # 4. Build Docker image (from Dockerfile in repo root)
      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t $IMAGE:$GIT_SHA -t $IMAGE:net-tools .

      # 5. Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # 6. Scan Docker image with Trivy
      - name: Scan image with Trivy
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH $IMAGE:net-tools

      # 7. Push Docker images (only if scan passes)
      - name: Push Docker image
        if: success()
        run: |
          docker push $IMAGE:net-tools